class AddObservationDiff < ActiveRecord::Migration[5.1]
  def change
    # Give us a place to put diffs generated by, e.g., check_please
    add_column "lab_tech_observations", "diff", :text
  end
end
